name = "PooksoftBase"
uuid = "17dff602-ea15-4a83-a4cd-e8c4e335a075"
authors = ["Jeffrey Varner <jvarner@pooksoft.com>"]
version = "1.2.0"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "~1.6"
